const ChatActionTypes = {
    MESSAGES_FROM_PROJECT_START: 'FETCH_MESSAGES_FROM_PROJECT',
    MESSAGES_FROM_PROJECT_SUCCESS: 'FETCH_MESSAGES_FROM_PROJECT_SUCCESS',
    CHAT_ERROR: 'CHAT_ERROR'
}

export default ChatActionTypes;