const UserActionTypes = {
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    PROJECT_FETCH_USER: 'PROJECT_FETCH_USER',
    PROJECT_FETCH_USER_SUCCESS: 'PROJECT_FETCH_USER_SUCCESS'
}

export default UserActionTypes;