const ProjectActionTypes = {
    PROJECT_ADD_START: 'PROJECT_ADD_START',
    PROJECT_ADD_SUCCESS: 'PROJECT_ADD_SUCCESS',
    PROJECT_ADD_FAILURE: 'PROJECT_ADD_FAILURE',
    PROJECT_FETCH_START: 'PROJECT_FETCH_START',
    PROJECT_FETCH_SUCCESS: 'PROJECT_FETCH_SUCCESS',
    PROJECT_FETCH_FAILURE: 'PROJECT_FETCH_FAILURE'
}

export default ProjectActionTypes;