const ProjectActionTypes = {
    PROJECT_ADD_START: 'PROJECT_ADD_START',
    PROJECT_ADD_SUCCESS: 'PROJECT_ADD_SUCCESS',
    PROJECT_ADD_FAILURE: 'PROJECT_ADD_FAILURE',
    PROJECT_FETCH_START: 'PROJECT_FETCH_START',
    PROJECT_FETCH_SUCCESS: 'PROJECT_FETCH_SUCCESS',
    PROJECT_FETCH_FAILURE: 'PROJECT_FETCH_FAILURE',
    PROJECT_CREATE_SHOW: 'PROJECT_CREATE_SHOW',
    PROJECT_CREATE_CLOSE: 'PROJECT_CREATE_CLOSE',
    PROJECT_FILTERED_ADD_START: 'PROJECT_FILTERED_ADD_START'
}

export default ProjectActionTypes;